version: "3.8"

services:
  dev_environment:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    user: root
    volumes:
      # Project root
      - .:/workspace:Z
      # Cargo
      - cargo_registry:/root/.cargo/registry
      - cargo_git:/root/.cargo/git
      - cargo_target:/workspace/target
      # Typst
      - typst_packages:/root/.local/share/typst/packages
    working_dir: /workspace
    # Keep container running
    command: sleep infinity

volumes:
  cargo_registry:
    name: cargo_registry
  cargo_git:
    name: cargo_git
  cargo_target:
  typst_packages:
    name: typst_packages
